name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Organize dependencies
      run: yarn
      run: yarn run bootstrap

    - name: Build
      run: yarn run build

    - name: Test
      run: yarn run test

    - name: Publish coverage
      uses: codecov/codecov-action@v1
        with:
          file: './packages/api/coverage/lcov.info'
